<a href="https://colab.research.google.com/github/esa-prakasa/autov/blob/master/binary_lane_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Load dan mount Google Drive
from google.colab import drive

# Pilihan user authorization dengan menggunakan account Google
drive.mount('/content/drive')

# Pilihan user authorization dengan menggunakan account Google
path = "/content/drive/My Drive/Colab Notebooks/dataset"
!ls -l "/content/drive/My Drive/Colab Notebooks/dataset"

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive
total 104924
-rw------- 1 root root      168 Feb  7 04:37  abc.csv
-rw------- 1 root root    46323 Feb 11 07:41  b15.jpg
-rw------- 1 root root   310090 Feb  7 04:18  juanda.jpg
-rw------- 1 root root  3780462 Feb  7 09:53  juantestbw.bmp
-rw------- 1 root root   993426 Feb  7 09:51  juantest.jpg
-rw------- 1 root root  2458120 Feb 11 07:41  keras_model.h5
-rw------- 1 root root       15 Feb 11 07:41  labels.txt
-rw------- 1 root root      151 Feb  7 04:32 'pi

In [2]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

dataset = pd.read_csv("/content/drive/My Drive/Colab Notebooks/dataset/road20pct_200.csv")
dataset.head(10)


/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


No   i   j    r    g   b   class
0   0   0   0   15   19  21       0
1   0   0   1   13   19  19       0
2   0   0   2   14   18  22       0
3   0   0   3   15   20  22       0
4   0   0   4   15   17  23       0
5   0   0   5   32   27  40       0
6   0   0   6   30   42  47       0
7   0   0   7   26   28  38       0
8   0   0   8   36   42  32       0
9   0   0   9   28   22  22       0

In [3]:
dataset.describe(include='all')

No              i  ...              b          class
count  282720.000000  282720.000000  ...  282720.000000  282720.000000
mean       14.500000      18.500000  ...      81.898048       0.437801
std         8.655457      10.965875  ...      51.978742       0.496117
min         0.000000       0.000000  ...       0.000000       0.000000
25%         7.000000       9.000000  ...      42.000000       0.000000
50%        14.500000      18.500000  ...      73.000000       0.000000
75%        22.000000      28.000000  ...     114.000000       1.000000
max        29.000000      37.000000  ...     255.000000       1.000000

[8 rows x 7 columns]

In [6]:
X= dataset.iloc[:,1:6]
Y= dataset.iloc[:,6]

print("Input")
print(X)
print("Target")
print(Y)


Input
         i    j    r    g   b
0        0    0   15   19  21
1        0    1   13   19  19
2        0    2   14   18  22
3        0    3   15   20  22
4        0    4   15   17  23
...     ..  ...  ...  ...  ..
282715  37  243   46   67  42
282716  37  244   28   32  27
282717  37  245   72   75  31
282718  37  246   56   47  38
282719  37  247   89  104  51

[282720 rows x 5 columns]
Target
0         0
1         0
2         0
3         0
4         0
         ..
282715    0
282716    0
282717    0
282718    0
282719    0
Name:  class, Length: 282720, dtype: int64


In [7]:
#standardizing the input feature
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

print(X)

[[-1.68705478 -1.72508076 -1.27577899 -1.27858135 -1.17159732]
 [-1.68705478 -1.71111249 -1.31114677 -1.27858135 -1.21007466]
 [-1.68705478 -1.69714423 -1.29346288 -1.29717154 -1.15235865]
 ...
 [ 1.68705478  1.69714423 -0.26779718 -0.23753066 -0.97921064]
 [ 1.68705478  1.71111249 -0.55073944 -0.758056   -0.84453997]
 [ 1.68705478  1.72508076  0.03282898  0.30158488 -0.59443728]]


In [0]:
from keras import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [16]:
from keras import optimizers

classifier = Sequential()

classifier.add(Dense(3, activation='relu', kernel_initializer='random_normal', input_dim=5))
classifier.add(Dense(3, activation='relu', kernel_initializer='random_normal'))
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

classifier.summary()
sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
#classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])
classifier.compile(optimizer ='sgd',loss='binary_crossentropy', metrics =['accuracy'])

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 3)                 18        
_________________________________________________________________
dense_12 (Dense)             (None, 3)                 12        
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 4         
Total params: 34
Trainable params: 34
Non-trainable params: 0
_________________________________________________________________


In [14]:
#Fitting the data to the training dataset
classifier.fit(X_train,y_train, batch_size=20, epochs=10)


# serialize model to JSON
model_json = classifier.to_json()
with open("/content/drive/My Drive/Colab Notebooks/dataset/road_model_20pct200.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
classifier.save_weights("/content/drive/My Drive/Colab Notebooks/dataset/road_wg_model_20pct200.h5")
print("Saved model to disk")

Epoch 1/10
226176/226176 [==============================] - 14s 62us/step - loss: 0.3971 - accuracy: 0.8133
Epoch 2/10
226176/226176 [==============================] - 13s 55us/step - loss: 0.3310 - accuracy: 0.8518
Epoch 3/10
226176/226176 [==============================] - 13s 57us/step - loss: 0.3282 - accuracy: 0.8531
Epoch 4/10
226176/226176 [==============================] - 13s 56us/step - loss: 0.3268 - accuracy: 0.8538
Epoch 5/10
226176/226176 [==============================] - 13s 57us/step - loss: 0.3243 - accuracy: 0.8555
Epoch 6/10
226176/226176 [==============================] - 13s 57us/step - loss: 0.3225 - accuracy: 0.8563
Epoch 7/10
226176/226176 [==============================] - 13s 57us/step - loss: 0.3218 - accuracy: 0.8568
Epoch 8/10
226176/226176 [==============================] - 13s 56us/step - loss: 0.3216 - accuracy: 0.8571
Epoch 9/10
226176/226176 [==============================] - 13s 56us/step - loss: 0.3212 - accuracy: 0.8564
Epoch 10/10
226176/226176 [=

In [0]:
eval_model=classifier.evaluate(X_train, y_train)
eval_model

197904/197904 [==============================] - 4s 18us/step


[0.28572549094537186, 0.8723016977310181]

In [0]:
print(X_test)
inData = X_test[0,:]
print(inData)

y_pred=classifier.predict(X_test)

inData = np.transpose(inData)
y_out = classifier.predict(inData)
print(y_out)

y_pred =(y_pred>0.5)

print(y_pred)

[[ 0.59274898 -1.44571545  0.82860409  0.61761813  0.63683748]
 [-0.77513328 -1.44571545  0.29808735  0.19004374  0.19434811]
 [-1.50467048 -0.39809556  1.11154635  1.04519253  1.0408495 ]
 ...
 [ 0.04559608 -0.11873025 -0.19706161 -0.21894046 -0.19042525]
 [ 1.50467048  0.77523872  1.34143694  1.39840616  1.48333887]
 [ 0.31917253 -0.11873025  0.86397187  1.17532386  0.86770149]]
[ 0.59274898 -1.44571545  0.82860409  0.61761813  0.63683748]


ValueError: ignored

In [0]:
y_pred=classifier.predict(X_test)
y_pred =(y_pred>0.5)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


T= sum(sum(cm))

cm=cm/T
print(cm)

acc = cm[0,0] + cm[1,1]
print(acc)

[[0.49169968 0.06983352]
 [0.05921053 0.37925627]]
0.870955951707225
