<a href="https://colab.research.google.com/github/esa-prakasa/autov/blob/master/binary_lane.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Load dan mount Google Drive
from google.colab import drive

# Pilihan user authorization dengan menggunakan account Google
drive.mount('/content/drive')

# Pilihan user authorization dengan menggunakan account Google
path = "/content/drive/My Drive/Colab Notebooks/dataset"
!ls -l "/content/drive/My Drive/Colab Notebooks/dataset"

In [5]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

dataset = pd.read_csv("/content/drive/My Drive/Colab Notebooks/dataset/road20pct_200.csv")
dataset.head(10)


No   i   j    r    g   b   class
0   0   0   0   15   19  21       0
1   0   0   1   13   19  19       0
2   0   0   2   14   18  22       0
3   0   0   3   15   20  22       0
4   0   0   4   15   17  23       0
5   0   0   5   32   27  40       0
6   0   0   6   30   42  47       0
7   0   0   7   26   28  38       0
8   0   0   8   36   42  32       0
9   0   0   9   28   22  22       0

In [6]:
dataset.describe(include='all')

No              i  ...              b          class
count  282720.000000  282720.000000  ...  282720.000000  282720.000000
mean       14.500000      18.500000  ...      81.898048       0.437801
std         8.655457      10.965875  ...      51.978742       0.496117
min         0.000000       0.000000  ...       0.000000       0.000000
25%         7.000000       9.000000  ...      42.000000       0.000000
50%        14.500000      18.500000  ...      73.000000       0.000000
75%        22.000000      28.000000  ...     114.000000       1.000000
max        29.000000      37.000000  ...     255.000000       1.000000

[8 rows x 7 columns]

In [11]:
X= dataset.iloc[:,1:6]
Y= dataset.iloc[:,6]

print("Input")
print(X)
print("Target")
print(Y)


Input
         i    j    r    g   b
0        0    0   15   19  21
1        0    1   13   19  19
2        0    2   14   18  22
3        0    3   15   20  22
4        0    4   15   17  23
...     ..  ...  ...  ...  ..
282715  37  243   46   67  42
282716  37  244   28   32  27
282717  37  245   72   75  31
282718  37  246   56   47  38
282719  37  247   89  104  51

[282720 rows x 5 columns]
Target
0         0
1         0
2         0
3         0
4         0
         ..
282715    0
282716    0
282717    0
282718    0
282719    0
Name:  class, Length: 282720, dtype: int64


In [13]:
#standardizing the input feature
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

print(X)

[[-1.68705478 -1.72508076 -1.27577899 -1.27858135 -1.17159732]
 [-1.68705478 -1.71111249 -1.31114677 -1.27858135 -1.21007466]
 [-1.68705478 -1.69714423 -1.29346288 -1.29717154 -1.15235865]
 ...
 [ 1.68705478  1.69714423 -0.26779718 -0.23753066 -0.97921064]
 [ 1.68705478  1.71111249 -0.55073944 -0.758056   -0.84453997]
 [ 1.68705478  1.72508076  0.03282898  0.30158488 -0.59443728]]


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3)

In [15]:
from keras import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [33]:
classifier = Sequential()

classifier.add(Dense(7, activation='relu', kernel_initializer='random_normal', input_dim=5))
classifier.add(Dense(5, activation='relu', kernel_initializer='random_normal'))
classifier.add(Dense(2, activation='relu', kernel_initializer='random_normal'))
classifier.add(Dense(1, activation='sigmoid', kernel_initializer='random_normal'))

classifier.summary()

classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_37 (Dense)             (None, 7)                 42        
_________________________________________________________________
dense_38 (Dense)             (None, 5)                 40        
_________________________________________________________________
dense_39 (Dense)             (None, 2)                 12        
_________________________________________________________________
dense_40 (Dense)             (None, 1)                 3         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


In [34]:
#Fitting the data to the training dataset
classifier.fit(X_train,y_train, batch_size=20, epochs=10)


# serialize model to JSON
model_json = classifier.to_json()
with open("/content/drive/My Drive/Colab Notebooks/dataset/road_model_20pct200.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
classifier.save_weights("/content/drive/My Drive/Colab Notebooks/dataset/road_wg_model_20pct200.h5")
print("Saved model to disk")

Epoch 1/10
197904/197904 [==============================] - 12s 58us/step - loss: 0.3868 - accuracy: 0.8226
Epoch 2/10
197904/197904 [==============================] - 12s 58us/step - loss: 0.3319 - accuracy: 0.8525
Epoch 3/10
197904/197904 [==============================] - 12s 60us/step - loss: 0.3102 - accuracy: 0.8648
Epoch 4/10
197904/197904 [==============================] - 12s 61us/step - loss: 0.3055 - accuracy: 0.8674
Epoch 5/10
197904/197904 [==============================] - 12s 62us/step - loss: 0.3036 - accuracy: 0.8671
Epoch 6/10
197904/197904 [==============================] - 12s 61us/step - loss: 0.3014 - accuracy: 0.8680
Epoch 7/10
197904/197904 [==============================] - 12s 61us/step - loss: 0.2979 - accuracy: 0.8688
Epoch 8/10
197904/197904 [==============================] - 11s 57us/step - loss: 0.2943 - accuracy: 0.8698
Epoch 9/10
197904/197904 [==============================] - 11s 58us/step - loss: 0.2909 - accuracy: 0.8700
Epoch 10/10
197904/197904 [=

In [35]:
eval_model=classifier.evaluate(X_train, y_train)
eval_model

197904/197904 [==============================] - 4s 18us/step


[0.28572549094537186, 0.8723016977310181]

In [37]:
y_pred=classifier.predict(X_test)
y_pred =(y_pred>0.5)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


T= sum(sum(cm))

cm=cm/T
print(cm)

acc = cm[0,0] + cm[1,1]
print(acc)

[[0.49169968 0.06983352]
 [0.05921053 0.37925627]]
0.870955951707225
